StockManagerBundle\Entity\Category:
    type: entity
    table: null
    uniqueConstraints:
        uniqueConstraint:
            columns: [category_name]
    repositoryClass: StockManagerBundle\Entity\CategoryRepository
    id:
        category_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category_name:
            type: string
            length: 255
        category_code:
            type: string
            length: 4
    oneToMany:
        items:
           targetEntity: Item
           mappedBy: category
   

