StockManagerBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: StockManagerBundle\Entity\ItemRepository
    id:
        item_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category_id:
            type: integer
        serial_no:
            type: string
            length: 255
        weight_g:
            type: integer
        weight_mg:
            type: integer
    manyToOne:
       category:
           targetEntity: Category
           inversedBy: items
           joinColumn: 
               name: category_id
               referencedColumnName: category_id
 
