## YAML Template.
---
StockManagerBundle\Entity\UserLog:
    type: entity
    table: null
    repositoryClass: StockManagerBundle\Entity\UserLogRepository
    id:
        log_id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user_id:
            type: integer
        category:
            type: string
            lenght: 255
        serial_no:
            type: string
            length: 255
        weight_g:
            type: integer
        weight_mg:
            type: integer
        date:
            type: datetime
        action:
            type: string
            length: 255
    manyToOne:
       user:
           targetEntity: User
           joinColumn: 
               name: user_id
               referencedColumnName: id