stock_manager_homepage:
    path:     /hello/{name}
    defaults: { _controller: StockManagerBundle:Default:index }
    
StockManagerBundle_add_category:
    pattern:  /addCategory
    defaults: { _controller: StockManagerBundle:Stock:addCategory }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_edit_category:
    pattern:  /editCategory/{category_id}
    defaults: { _controller: StockManagerBundle:Stock:editCategory }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_add_item:
    pattern:  /addItem
    defaults: { _controller: StockManagerBundle:Stock:addItem }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_edit_item:
    pattern:  /editItem/{item_id}
    defaults: { _controller: StockManagerBundle:Stock:editItem }
    requirements:
        _method:  GET|POST

StockManagerBundle_delete_item:
    pattern:  /deleteItem/{item_id}
    defaults: { _controller: StockManagerBundle:Stock:deleteItem }
    requirements:
        _method:  GET|POST

StockManagerBundle_delete_category:
    pattern:  /deleteCategory/{category_id}
    defaults: { _controller: StockManagerBundle:Stock:deleteCategory }
    requirements:
        _method:  GET|POST

StockManagerBundle_add_sales:
    pattern:  /addSales
    defaults: { _controller: StockManagerBundle:Stock:addSales }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_view_reports:
    pattern:  /viewReport
    defaults: { _controller: StockManagerBundle:Stock:viewReport }
    requirements:
        _method:  GET|POST

StockManagerBundle_get_item_serials_by_category:
    pattern:  /getItemsByCategoryName
    defaults: { _controller: StockManagerBundle:Stock:getItemSerialsByCategoryName }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_get_item_weight_by_serial:
    pattern:  /getItemWeightBySerial
    defaults: { _controller: StockManagerBundle:Stock:getItemWeightBySerial }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_view_user_logs:
    pattern:  /viewUserLogs
    defaults: { _controller: StockManagerBundle:Stock:viewUserLogs }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_set_next_serialNoBy_category:
    pattern:  /setNextSerialNoByCategory
    defaults: { _controller: StockManagerBundle:Stock:setNextSerialNoByCategory }
    requirements:
        _method:  GET|POST


StockManagerBundle_view_summary:
    pattern:  /viewSummary
    defaults: { _controller: StockManagerBundle:Stock:viewSummary }
    requirements:
        _method:  GET|POST

StockManagerBundle_view_total_stock_weight:
    pattern:  /viewTotalStockWeight
    defaults: { _controller: StockManagerBundle:Stock:viewTotalStockWeight }
    requirements:
        _method:  GET|POST

