stock_manager_homepage:
    path:     /hello/{name}
    defaults: { _controller: StockManagerBundle:Default:index }
    
StockManagerBundle_add_category:
    pattern:  /addCategory
    defaults: { _controller: StockManagerBundle:Stock:addCategory }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_edit_category:
    pattern:  /editCategory/{category_id}
    defaults: { _controller: StockManagerBundle:Stock:editCategory }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_add_item:
    pattern:  /addItem
    defaults: { _controller: StockManagerBundle:Stock:addItem }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_edit_item:
    pattern:  /editItem/{item_id}
    defaults: { _controller: StockManagerBundle:Stock:editItem }
    requirements:
        _method:  GET|POST

StockManagerBundle_add_sales:
    pattern:  /addSales
    defaults: { _controller: StockManagerBundle:Stock:addSales }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_view_reports:
    pattern:  /viewReport
    defaults: { _controller: StockManagerBundle:Stock:viewReport }
    requirements:
        _method:  GET|POST

StockManagerBundle_get_item_serials_by_category:
    pattern:  /getItemsByCategoryName
    defaults: { _controller: StockManagerBundle:Stock:getItemSerialsByCategoryName }
    requirements:
        _method:  GET|POST
        
StockManagerBundle_get_item_weight_by_serial:
    pattern:  /getItemWeightBySerial
    defaults: { _controller: StockManagerBundle:Stock:getItemWeightBySerial }
    requirements:
        _method:  GET|POST
        
    